#version 310 es

precision mediump float;
precision mediump image2D;
layout(local_size_x=64) in;

layout(binding=0, rgba8) readonly uniform image2D src;
layout(binding=1, rgba8) writeonly uniform image2D dst;
uniform uvec4 uConsts[2];

#define A_GPU 1
#define A_GLSL 1

#include "ffx_a.h"

AF3 CasLoad(ASU2 p)
{
  return imageLoad(src, p).rgb;
}

void CasInput(inout AF1 r, inout AF1 g, inout AF1 b) {}

#include "ffx_cas.h"

void main() {
  // Do remapping of local xy in workgroup for a more PS-like swizzle pattern.
  AU2 gxy = ARmp8x8(gl_LocalInvocationID.x) + AU2(gl_WorkGroupID.x << 4u, gl_WorkGroupID.y << 4u);

  // Filter.
  AF4 c;
  CasFilter(c.r, c.g, c.b, gxy, uConsts[0], uConsts[1], true);
  imageStore(dst, ASU2(gxy), c);
  gxy.x += 8u;

  CasFilter(c.r, c.g, c.b, gxy, uConsts[0], uConsts[1], true);
  imageStore(dst, ASU2(gxy), c);
  gxy.y += 8u;

  CasFilter(c.r, c.g, c.b, gxy, uConsts[0], uConsts[1], true);
  imageStore(dst, ASU2(gxy), c);
  gxy.x -= 8u;

  CasFilter(c.r, c.g, c.b, gxy, uConsts[0], uConsts[1], true);
  imageStore(dst, ASU2(gxy), c);
}
